/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.animation;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.TiViewProxy;
import org.appcelerator.titanium.view.TiCompositeLayout;
import org.appcelerator.titanium.view.TiCompositeLayout.LayoutArrangement;
import org.appcelerator.titanium.view.TiUIView;
import android.widget.ImageView.ScaleType;
import android.view.LayoutInflater;
import android.view.View;
import android.content.res.Resources;
import com.airbnb.lottie.LottieAnimationView;
import com.airbnb.lottie.*;
import android.app.Activity;
import android.animation.Animator;
import android.animation.ValueAnimator;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.titanium.io.TiBaseFile;
import org.appcelerator.titanium.io.TiFileFactory;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.IOException;
import java.lang.Exception;
import org.json.JSONObject;
import android.os.Message;
import org.appcelerator.kroll.common.TiMessenger;
import org.appcelerator.kroll.common.AsyncResult;
import java.util.HashMap;
import org.appcelerator.kroll.KrollFunction;
import java.lang.Float;

public class LottieView extends TiUIView {
	
	private static final String LCAT = "LottieViewProxy";
	private static final boolean DBG = TiConfig.LOGD;
	
	private Resources resources;
	private LottieAnimationView lottieView;
	private TiViewProxy proxy;
	private KrollFunction callbackUpdate = null;
	private KrollFunction callbackComplete = null;
	private KrollFunction callbackReady = null;
	private float initialDuration = 0;
	public LottieView(TiViewProxy proxy) {
		super(proxy);
		
		this.proxy = proxy;
		String packageName = proxy.getActivity().getPackageName();
		resources = proxy.getActivity().getResources();
		View viewWrapper;

		int resId_viewHolder = -1;
		int resId_lotti = -1;

		resId_viewHolder = resources.getIdentifier("layout_lottie", "layout", packageName);
		resId_lotti = resources.getIdentifier("animation_view", "id", packageName);

		LayoutInflater inflater = LayoutInflater.from(proxy.getActivity());
		viewWrapper = inflater.inflate(resId_viewHolder, null);

		lottieView = (LottieAnimationView)viewWrapper.findViewById(resId_lotti);
		setNativeView(viewWrapper);

		setScaleMode(TiConvert.toString(proxy.getProperty("scaleMode")));
		lottieView.addAnimatorUpdateListener(new AnimatorUpdateListener());
		lottieView.addAnimatorListener(new AnimatorListener());
		if (TiConvert.toBoolean(proxy.getProperty("disableHardwareAcceleration"))) {
			lottieView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
		} else {
			lottieView.setLayerType(View.LAYER_TYPE_HARDWARE, null);
		}
		lottieView.enableMergePathsForKitKatAndAbove(TiConvert.toBoolean(proxy.getProperty("mergePath")));
	}

	@Override
	public void processProperties(KrollDict d) {
		super.processProperties(d);
		
		if (d.containsKey("file")) {
			if (TiApplication.isUIThread()) {
				loadFile(d.getString("file"));
			} else {
				TiMessenger.sendBlockingMainMessage(proxy.getMainHandler().obtainMessage(LottieViewProxy.MSG_LOADFILE, d.getString("file")));
			}
		} else if (d.containsKey("scaleMode")) {
			setScaleMode(d.getString("scaleMode"));
		} else if (d.containsKey("disableHardwareAcceleration")) {
			if (d.getBoolean("disableHardwareAcceleration")) {
				lottieView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
			} else {
				lottieView.setLayerType(View.LAYER_TYPE_HARDWARE, null);
			}
		} else if(d.containsKey("loop")) {
			lottieView.loop(d.getBoolean("loop"));
		} else if(d.containsKey("update")) {
			callbackUpdate =(KrollFunction) d.get("update");
		} else if(d.containsKey("ready")) {
			callbackReady =(KrollFunction) d.get("ready");
		}  else if(d.containsKey("complete")) {
			callbackComplete =(KrollFunction) d.get("complete");
		} else if(d.containsKey("mergePath")) {
			lottieView.enableMergePathsForKitKatAndAbove(d.getBoolean("mergePath"));
		} else if(d.containsKey("progress")) {
			setProgress(Float.parseFloat(d.getString("progress")));
		}
	}
	
	private void setScaleMode(String smode) {
		// Set scale mode on view
		//
		if (smode.equals("center")) {
			lottieView.setScaleType( ScaleType.CENTER);
		} else if (smode.equals("centerCrop")) {
			lottieView.setScaleType( ScaleType.CENTER_CROP);
		} else if (smode.equals("centerInside")) {
			lottieView.setScaleType( ScaleType.CENTER_INSIDE);
		} else {
			lottieView.setScaleType( ScaleType.CENTER_INSIDE);
		}
	}
	
	public void loadFile(String f) {
		String url = proxy.resolveUrl(null, f);
		TiBaseFile file = TiFileFactory.createTitaniumFile(new String[] { url }, false);
		
		if (file.exists()) {
			try {
				InputStream stream = file.getInputStream();
				int size = stream.available();
				byte[] buffer = new byte[size];
				stream.read(buffer);
				String json = new String(buffer, "UTF-8");
				JSONObject jsonObject = new JSONObject(json);
				proxy.setProperty("width",jsonObject.optInt("w", 0));
				proxy.setProperty("height",jsonObject.optInt("h", 0));
			} catch (Exception e) {
				Log.e(LCAT, "Couldn't read width/height");
			}

			LottieComposition.Factory.fromAssetFileName(TiApplication.getInstance(), url.replaceAll("file:///android_asset/", ""), new OnCompositionLoadedListener() {
				@Override
				public void onCompositionLoaded(LottieComposition composition) {
					Log.i(LCAT, "loaded: " + lottieView);
					lottieView.setComposition(composition);
					lottieView.setImageAssetsFolder(TiConvert.toString(proxy.getProperty("assetFolder")));

					lottieView.addAnimatorUpdateListener(new AnimatorUpdateListener());
					lottieView.addAnimatorListener(new AnimatorListener());

					initialDuration = lottieView.getDuration();
					proxy.setProperty("duration", initialDuration);
					
					if (TiConvert.toBoolean(proxy.getProperty("loop"))) {
						lottieView.loop(true);
					}
					if (TiConvert.toBoolean(proxy.getProperty("autoStart"))) {
						lottieView.playAnimation();
					}

					if (callbackReady != null) {
						HashMap<String,Object> event = new HashMap<String, Object>();
						callbackReady.call(proxy.getKrollObject(), event);
					}
				}
			});

		} else {
			Log.e(LCAT, "File "+file.name()+" not found!");
		}
	}
	
	
	
	protected class AnimatorUpdateListener implements ValueAnimator.AnimatorUpdateListener
	{
		public void onAnimationUpdate(ValueAnimator animation)
		{
			animationEvent(animation.getAnimatedFraction(), LottieViewProxy.ANIMATION_RUNNING);
		}
	}

	protected class AnimatorListener implements Animator.AnimatorListener {
		public void onAnimationStart(Animator animation) {
			 animationEvent(getProgress(), LottieViewProxy.ANIMATION_START);
		}

		public void onAnimationEnd(Animator animation) {
			if (getProgress()>=1) {
				animationEvent(getProgress(), LottieViewProxy.ANIMATION_END);
				if (callbackComplete != null) {
					HashMap<String,Object> event = new HashMap<String, Object>();
					event.put("status", LottieViewProxy.ANIMATION_END);
						callbackComplete.call(proxy.getKrollObject(), event);
				}
			}
		}

		public void onAnimationCancel(Animator animation) {
			 animationEvent(getProgress(), LottieViewProxy.ANIMATION_CANCEL);
		}

		public void onAnimationRepeat(Animator animation) {
			 animationEvent(getProgress(), LottieViewProxy.ANIMATION_REPEAT);
		}
	}

	private void animationEvent(float percentage, int status) {
		if (callbackUpdate != null && !TiConvert.toBoolean(proxy.getProperty("pause"))) {
			HashMap<String,Object> event = new HashMap<String, Object>();
			event.put("time", TiConvert.toFloat(proxy.getProperty("duration"))*percentage);
			event.put("percentage", percentage);
			event.put("status", status);
			callbackUpdate.call(proxy.getKrollObject(), event);
		}
	}
	
	public void startAnimation() {
		boolean restart = lottieView.isAnimating();
		lottieView.cancelAnimation();
		lottieView.setProgress(0f);

		if (TiConvert.toFloat(proxy.getProperty("duration")) == 0 || TiConvert.toFloat(proxy.getProperty("duration")) == initialDuration) {
			lottieView.playAnimation();
		} else {
			ValueAnimator va = ValueAnimator.ofFloat(0f, 1f);
			va.setDuration((long)TiConvert.toFloat(proxy.getProperty("duration")));

			va.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
				public void onAnimationUpdate(ValueAnimator animation) {
					lottieView.setProgress( (Float)animation.getAnimatedValue() );
					animationEvent(animation.getAnimatedFraction(), LottieViewProxy.ANIMATION_RUNNING);
				}
			});
			va.start();
		}
	}
	
	@Kroll.setProperty @Kroll.method
	public void setProgress(float val) {
		lottieView.setProgress(val);
	}

	@Kroll.getProperty @Kroll.method
	public float getProgress() {
		return lottieView.getProgress();
	}
	
	@Kroll.method
	public void start() {
		proxy.setProperty("pause",false);
		if (TiApplication.isUIThread()) {
			startAnimation();
		} else {
			TiMessenger.sendBlockingMainMessage(proxy.getMainHandler().obtainMessage(LottieViewProxy.MSG_STARTANIMATION));
		}
	}

}
