/*
  This file was auto-generated by the Titanium Module SDK helper for Android
  Appcelerator Titanium Mobile
  Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
  Licensed under the terms of the Apache Public License
  Please see the LICENSE included with this distribution for details.
 */
package ti.animation;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.annotations.Kroll.module;

@module(name = "TiAnimation", id = "ti.animation")
public class TiAnimationModule extends KrollModule {
    @Kroll.constant
    static final int ANIMATION_LOTTIE = 0;
    @Kroll.constant
    static final int ANIMATION_RIVE = 1;
}
